services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_WS_URL=ws://localhost:8000/ws/realtime
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: app-network
