services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CREDENTIALS_PATH=/app/credentials.json
      - GOOGLE_TOKEN_PATH=/app/token.json
    volumes:
      - ../backend:/app:cached
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_WS_URL=ws://localhost:8000/ws/realtime
    depends_on:
      - backend
    restart: unless-stopped
